server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://1.14.110.117:3306/wxm_msfast?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: Mo5497071966@
    driver-class-name: com.mysql.cj.jdbc.Driver
